---
- name: Load OS variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install MariaDB
  package:
    name: "{{ mariadb_packages }}"
    state: present

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes