---
- name: Install MariaDB
  package:
    name:
      - mariadb-server
      - python3-pymysql
    state: present

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes