---
- name: Load OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install MariaDB packages
  package:
    name: "{{ mariadb_packages }}"
    state: present
  become: true

- name: Ensure MariaDB service is started
  service:
    name: mariadb
    state: started
    enabled: yes
  become: true

# ----------------------------------------------------
# Fix root authentication for fresh install (RedHat)
# ----------------------------------------------------
- name: Ensure root uses mysql_native_password on RedHat
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    plugin: mysql_native_password
    state: present
  login_unix_socket: /var/lib/mysql/mysql.sock
  when: ansible_os_family == "RedHat"
  become: true

# ----------------------------------------------------
# Create WordPress database (all OS)
# ----------------------------------------------------
- name: Create WordPress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: true

# ----------------------------------------------------
# Create WordPress user (all OS)
# ----------------------------------------------------
- name: Create WordPress user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  become: true